filebeat.inputs:
  - type: log
    enabled: true
    paths: 
      - /var/log/*.log
      #- /var/log/*.json
    #reload.enabled: true
    #reload.period: 10s
#- type: json
 # paths:
  #  - /var/log/*.json
    #json.message_key: "message"
    #json.keys_under_root: true
    #json.overwrite_keys: true

    exclude_lines: ["^www.three.com"]
    multiline.pattern: ^www.*
    multiline.negate: true
    multiline.match: after

setup.kibana:
  host: kibana:5601
  username: elastic
  password: 1234
  

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: 1234
  index: "ngis-%{+yyyy.MM.dd}"

output.logstash:
  hosts: ["logstash_host:5044"]
#output.console:
#  pretty: true

setup.template.enabled: false
setup.ilm.enabled: false
ilm.enabled: false
setup.template.overwrite: false
setup.template.name: "ngis"
setup.template.pattern: "ngis-*"
setup.dashboards.enabled: true
setup.template.settings.index.lifecycle.rollover_alias: "ngis"
setup.template.settings.index.lifecycle.name: "beats-default-policy"
