filebeat.inputs:
  - type: log
    enabled: true
    paths: 
      - /var/log/core*.log
    fields:
      tags: core

  - type: log
    enabled: true
    paths: 
      - /var/log/dataset*.log
    fields:
      tags: dataset

#      - /var/log/*.json
#    reload.enabled: true
#    reload.period: 10s
#- type: json
#  paths:
#    - /var/log/*.json
#    json.message_key: "message"
#    json.keys_under_root: true
#    json.overwrite_keys: true

#    exclude_lines: ["^www.three.com"] # Excluir las que empiecen por www.three.com
#    multiline.pattern: ^www.* #Comience por www. y cualquier cosa
#    multiline.negate: true #Negar el patrón para encontrar las que no coincidan con el evento
#    multiline.match: after #Añadir lo que no coincida con el patrón al evento anterior

setup.kibana:
  host: kibana:5601
  username: elastic
  password: 1234

#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
#  username: elastic
#  password: 1234
#  index: "ngis-%{+yyyy.MM.dd}"

output.logstash:
  hosts: ["logstash_host:5044"]
  #bulk_max_size: 100
  client_inactivity_timeout: 360


#output.console:
#  pretty: true

